# Melinda node tests

name: Melinda node tests

on: [push, workflow_call]

jobs:
  build-node-versions:
    name: Node version matrix
    runs-on: kk
    container: docker://node:14

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        NPM_CONFIG_IGNORE_SCRIPTS: true
    - run: npm audit --package-lock-only --production --audit-level=moderate
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present

  njsscan:
    name: Njsscan check
    needs: build-node-versions
    runs-on: kk
    container: docker://node:14

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
