# Melinda node tests

name: Melinda node tests

on: push

jobs:
  build-node-versions:
    name: Node version matrix
    runs-on: ubuntu-latest
    container: docker://node:14

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        NPM_CONFIG_IGNORE_SCRIPTS: true
    - run: npm audit --package-lock-only --production --audit-level=moderate
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present

  njsscan:
    name: Njsscan-check
    runs-on: ubuntu-latest
    container: docker://node:14

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'

  publish-npm:
    needs: [build-node-versions, njsscan]
    runs-on: ubuntu-latest
    # container: docker://node:14
    if: ${{ github.ref_name == 'v[1-9]+.*' }}

    steps:
    - name: Echo github obj
      run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      # - uses: melinda-node-tests.yml
      # - uses: actions/checkout@v2
      # # Setup .npmrc file to publish to npm
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.x'
      #     registry-url: 'https://registry.npmjs.org'
      # - run: npm ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.MELINDA_REST_API_CLIENT_NPM_TOKEN }}